### ISSUE TITLE
[EPIC] Rec-cloud requested features

### ISSUE THREAD

**Issue by kenpusney** [rec-framework/rec-core#46]
Features:
- CSV loader accepts Reader/InputStream instead of File.
- Scripting.runScript accepts Reader/InputStream instead of file name.
- ExecutionContext / 'rec' module should only shared by every scripting instance instead of static/global.
- Add Resource interface which provides Source directly.

**Comment by kenpusney** [comment]
- [x] CSV loader accepts Reader/InputStream instead of File.
- [ ] Scripting.runScript accepts Reader/InputStream instead of file name.
- [x] ExecutionContext / 'rec' module should only shared by every scripting instance instead of static/global.
- [ ] Add Resource interface which provides Source directly.
